---
title: "C 2"
format: html
editor: visual
---

## Administración de Riesgos

El proceso de la administración de riesgos implica , en primer lugar , la identificación de riesgos, y en segundo , su cuantificación y control mediante el establecimiento de límites de tolerancia para después mitigarlos mediante alguna estrategia de disminución de exposición.

## 

## Tipología de Riesgos

Bloques Básicos de riesgo:

-   **Riesgos de Negocio / Operativos**

    -   Tipología de Riesgos Financieros:

        -   Riesgos de producción

        -   Riesgos de personal

        -   Riesgos de Sistemas

        -   Riesgos de acontecimientos

-   **Riesgos Financieros**

    -   Tipología de Riesgos Financieros:
        -   Riesgo de crédito o de solvencia
        -   Riesgo de Liquidez
        -   Riesgo de Contrapartida o riesgos de liquidación
        -   Riesgo de Reinversión
        -   Riesgo de Sistema

-   **Riesgo de Entorno:**

    -   Tipología de Riesgo de Entorno:

        -   Riesgo Legal

        -   Riesgo Reputacional

        -   Riesgo país

## Riesgo de Mercado

**Riesgo de Mercado:**

-   Riesgo de incurrir en pérdidas por la variación en los precios de un activo financiero.

## Medidas de Riesgo: Value at Risk

**VaR (Value at Risk) :** Máxima pérdida esperada que puede sufrir un portafolio durante un período de timepo específico y con un nivel de confianza dado.

-   Nos ayuda a saber cuánto dinero podemos perder, en caso de que suceda un evento\
    extremo (“black swan”).

-   En la práctica, se usa para establecer un nivel máximo de pérdida que podemos asumir, esto depende de la aversión al riesgo de nuestros clientes.\
